### ISSUE TITLE
check error and indel tolerance for aligner at 5'

### ISSUE THREAD

**Issue by cmeesters** [cmeesters/ncap#17]

**Comment by cmeesters** [comment]
Hallo Benny,

ist das überhaupt ein Bug?

Wenn der Aligner angeworfen wird, gehen der ges. Adaptor ab 5' ins Alignment. Demzufolge werden auch etwaige Fehler und Indels downstream (Richtung 5' des Reads) berücksichtigt und gem. der Einstellungen ausgewertet.

Gibt es Fehler im Read downstream über 5' des Adaptormatches hinaus, kann das beim Trimming nicht berücksichtigt werden - erst Fehlerkorrekturroutinen können da greifen.

Was denkst Du? (War das überhaupt klar?)

Gruß,
Christian

**Comment by benrieger** [comment]
Hi Christian,


bin im "Urlaub". schau ich mir nächste woche an.


gruß


Benny


Benjamin Rieger
Dipl.- Bioinformatiker (FH)

Institut für Molekulargenetik, IMSB
Johannes-Gutenberg-Universität Mainz

Johann-Joachim-Becherweg 32
D-55128 Mainz

Tel: +49 6131 39 -25342 / -25465
Fax: +49 6131 39 -25346


________________________________
Von: Christian Meesters <notifications@github.com>
Gesendet: Mittwoch, 19. Oktober 2016 15:30
An: cmeesters/ncap
Cc: Rieger, Benjamin; Assign
Betreff: Re: [cmeesters/ncap] check error and indel tolerance for aligner at 5' (#17)


Hallo Benny,

ist das überhaupt ein Bug?

Wenn der Aligner angeworfen wird, gehen der ges. Adaptor ab 5' ins Alignment. Demzufolge werden auch etwaige Fehler und Indels downstream (Richtung 5' des Reads) berücksichtigt und gem. der Einstellungen ausgewertet.

Gibt es Fehler im Read downstream über 5' des Adaptormatches hinaus, kann das beim Trimming nicht berücksichtigt werden - erst Fehlerkorrekturroutinen können da greifen.

Was denkst Du? (War das überhaupt klar?)

Gruß,
Christian

-
